fos_rest:
  routing_loader:
    default_format: html
    include_format: true

  format_listener:
    enabled: true
    rules:
      - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: '^/user', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
      - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }
  view:
    view_response_listener: true
#  body_converter:
#    enabled: true
#  param_fetcher_listener: force
  body_listener:
    #array_normalizer:
      #service: fos_rest.normalizer.camel_keys
      #forms: true
